### PR TITLE
ST7036.h - class should implement interface LCD

### PR DESCRIPTION
**Pull request by mwallnoefer**
Other includes are unneeded, already done by LCD.h

### CODE REVIEW

**Comment by mwallnoefer** [comment]
Any news on this one?

**Comment by pkourany** [comment]
@mwallnoefer, did you get a chance to test the changes?

**Comment by mwallnoefer** [comment]
Yes, I tested it.

I am not saying that it is not working atm, but currently you have no real use for the class LCD in lcd.h. Applying my patch it would become the interface (abstract class) of the ST7306LCD class which opens it to polymorphism.

That means statements like `LCD *lcd = new ST7306LCD(...);` become possible to provide a useful abstraction between different kind of displays and interchangeability with other drivers.

**Comment by pkourany** [comment]
@mwallnoefer, sounds good!  I did not create this library, I simply ported it some time ago for the Particle platform.  I'll gladly merge your PR.  Thanks!

**Pull request merged**
